### ISSUE TITLE
Any sql file for this ???

### ISSUE THREAD

**Issue by asfaran** [kenwbauer/facebookapp#1]
Hi 
I can't find a way to use this !!!
its showing sql error ,,,,

**Comment by wickedthetoy** [comment]
Hi asfaran,
you need to connect to your Database (MySQL).
And this project work only with Public group !

**Comment by asfaran** [comment]
Hi Ken Bauer/Wickdthetoy

Actually this project haven't any database creation script/sql dump ..anything ,,
i am creating a database looking at code's 

if u had chance please ,can You explain what u meaned by public group ???

**Comment by wickedthetoy** [comment]
For the database we didn't create any kind of script/sql dump . Sorry

For the facebook group. You have 3 groups styles (Public, Private, Secret), you can find this information in the facebook group information. 

This code work only with Public group, because we didn't create facebook app who can give us information from all kind of group.

**Comment by asfaran** [comment]
Thanks,Just now i understood!!!

**Comment by wickedthetoy** [comment]
You welcome ! Have a good day !
